dir=/mnt/Nueva/Aria2
input-file=/home/alex/.config/aria2/aria2.session
save-session=/home/alex/.config/aria2/aria2.session
enable-rpc=true
rpc-allow-origin-all=true
rpc-listen-all=true
max-connection-per-server=16
split=16
