alias ll='lsd -lh --group-dirs=first'
alias la='lsd -a --group-dirs=first'
alias l='lsd --group-dirs=first'
alias lla='lsd -lha --group-dirs=first'
alias ls='lsd --group-dirs=first'
#alias cat='/usr/bin/bat --paging=never'
alias cat='/usr/bin/batcat --paging=never'
alias catn='/bin/cat'
#alias catnl='/usr/bin/batcat'
alias catnl='/usr/bin/bat'
