 # Opción A: Escuchar en todas las interfaces de red (IPv4)
 bind_to_address "0.0.0.0" 
 # Mantén el socket pero asegúrate de que sea una ruta absoluta para evitar líos
 bind_to_address "/home/alex/.mpd/socket"
 #bind_to_address "/tmp/mpd.socket"
 #bind_to_address "127.0.0.1"
 #bind_to_address "0.0.0.0"
 #bind_to_address "192.168.1.7"
 #bind_to_address "~/.mpd/socket"
 music_directory "~/Music"
 # Estas dos líneas son vitales para que MPD salga de ~/Music hacia /mnt/
 follow_outside_symlinks    "yes"
 follow_inside_symlinks     "yes"
 playlist_directory "~/.mpd/playlists"   
 db_file      "~/.mpd/mpd.db"  
 log_file      "~/.mpd/mpd.log"  
 pid_file      "~/.mpd/mpd.pid"  
 state_file     "~/.mpd/mpdstate"  
 user				"alex"
 #metadata_to_use  "artist, title" 
 metadata_to_use "artist, title, album, genre, albumartist, date"
audio_output {
    type        "pipewire"
    name        "PipeWire Output"
    mixer_type  "software"
}

audio_output {
    type                    "fifo"
    name                    "my_fifo"
    path                    "/tmp/mpd.fifo"
    format                  "48000:16:2"
}
