[FileDialog]
history=file:///mnt/Nueva/Aria2/Regreso al Planeta de los Simios (1975-1976)
lastVisited=file:///mnt/Nueva/Aria2/Regreso al Planeta de los Simios (1975-1976)
qtVersion=5.15.15
shortcuts=file:, file:///home/alex, file:///home/alex/Desktop, file:///home/alex/Downloads, file:///home/alex/Music, file:///home/alex/Documents/lmms
sidebarWidth=184
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xec\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xff\0\0\0\x1\0\0\0\0\0\0\0?\0\0\0\x1\0\0\0\0\0\0\0@\0\0\0\x1\0\0\0\0\0\0\0n\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)
viewMode=Detail
